[package]
name = "br-ow-ser"
version = "0.0.1"
authors = ["Raul Andrade <theandraderaul@gmail.com>"]
edition = "2021"

[[bin]]
name = "br-ow-ser"
path = "src/main.rs"

[dependencies]
getopts = "0.2.21"
image = "0.24.7"
serde = {version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"

